#!/usr/bin/env bash
# Render a BIRD 2 bird.conf for a Vultr BGP session from an env file.
#
# Usage:
#   ./scripts/render-bird-conf.sh vultr-bgp.env > bird.conf
#
# Supports IPv4-only, IPv6-only, or dual-stack based on which SOURCE_IPv*
# and ANNOUNCE_IPv*_PREFIXES are set.

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <env-file>" >&2
    exit 2
fi

ENV_FILE="$1"
if [[ ! -f "$ENV_FILE" ]]; then
    echo "env file not found: $ENV_FILE" >&2
    exit 2
fi

# shellcheck disable=SC1090
set -a
. "$ENV_FILE"
set +a

# ---- Defaults / validation --------------------------------------------------

: "${VULTR_PLATFORM:=vps}"
: "${LOCAL_ASN:?LOCAL_ASN is required}"
: "${BGP_PASSWORD:?BGP_PASSWORD is required}"
: "${ROUTER_ID:?ROUTER_ID is required}"

SOURCE_IPV4="${SOURCE_IPV4:-}"
SOURCE_IPV6="${SOURCE_IPV6:-}"
ANNOUNCE_IPV4_PREFIXES="${ANNOUNCE_IPV4_PREFIXES:-}"
ANNOUNCE_IPV6_PREFIXES="${ANNOUNCE_IPV6_PREFIXES:-}"

case "$VULTR_PLATFORM" in
    vps)
        VULTR_ASN=64515
        VULTR_NEIGHBOR_V4="169.254.169.254"
        ;;
    bare-metal)
        VULTR_ASN=20473
        VULTR_NEIGHBOR_V4="169.254.1.1"
        ;;
    *)
        echo "VULTR_PLATFORM must be 'vps' or 'bare-metal' (got '$VULTR_PLATFORM')" >&2
        exit 2
        ;;
esac
VULTR_NEIGHBOR_V6="2001:19f0:ffff::1"

if [[ -z "$SOURCE_IPV4" && -z "$SOURCE_IPV6" ]]; then
    echo "At least one of SOURCE_IPV4 or SOURCE_IPV6 must be set" >&2
    exit 2
fi

# ---- Helpers ----------------------------------------------------------------

emit_static_block() {
    # $1 = af keyword (ipv4|ipv6), $2 = space-separated prefixes, $3 = name
    local af="$1" prefixes="$2" name="$3"
    [[ -z "$prefixes" ]] && return 0

    printf 'protocol static %s {\n' "$name"
    printf '    %s;\n' "$af"
    for p in $prefixes; do
        printf '    route %s reject;\n' "$p"
    done
    printf '}\n\n'
}

emit_prefix_filter() {
    # $1 = filter name, $2 = af keyword, $3 = prefixes
    local name="$1" af="$2" prefixes="$3"
    printf 'filter %s {\n' "$name"
    if [[ -n "$prefixes" ]]; then
        printf '    if net ~ [\n'
        local first=1
        for p in $prefixes; do
            if [[ $first -eq 1 ]]; then
                printf '        %s' "$p"
                first=0
            else
                printf ',\n        %s' "$p"
            fi
        done
        printf '\n    ] then accept;\n'
    fi
    printf '    reject;\n'
    printf '}\n\n'
}

# ---- Output -----------------------------------------------------------------

cat <<EOF
###############################################################################
# Generated by scripts/render-bird-conf.sh - do not edit by hand.
# Platform: ${VULTR_PLATFORM}   Vultr ASN: ${VULTR_ASN}
###############################################################################

router id ${ROUTER_ID};

log syslog all;

protocol device {
    scan time 10;
}

protocol direct {
    ipv4;
    ipv6;
    interface "lo", "dummy*", "eth*", "ens*", "eno*";
}

protocol kernel kernel4 {
    ipv4 {
        export all;
    };
    learn;
}

protocol kernel kernel6 {
    ipv6 {
        export all;
    };
    learn;
}

EOF

# Static origin routes (for prefixes we announce)
emit_static_block "ipv4" "$ANNOUNCE_IPV4_PREFIXES" "static_ipv4"
emit_static_block "ipv6" "$ANNOUNCE_IPV6_PREFIXES" "static_ipv6"

# Per-AF export filters that only emit our own prefixes
emit_prefix_filter "vultr_export_ipv4" "ipv4" "$ANNOUNCE_IPV4_PREFIXES"
emit_prefix_filter "vultr_export_ipv6" "ipv6" "$ANNOUNCE_IPV6_PREFIXES"

# IPv4 BGP session
if [[ -n "$SOURCE_IPV4" ]]; then
    cat <<EOF
protocol bgp vultr_ipv4 {
    description "Vultr ${VULTR_PLATFORM} IPv4";
    local ${SOURCE_IPV4} as ${LOCAL_ASN};
    neighbor ${VULTR_NEIGHBOR_V4} as ${VULTR_ASN};
    multihop 2;
    password "${BGP_PASSWORD}";

    ipv4 {
        import all;
        export filter vultr_export_ipv4;
        next hop self;
    };
}

EOF
fi

# IPv6 BGP session
if [[ -n "$SOURCE_IPV6" ]]; then
    cat <<EOF
protocol bgp vultr_ipv6 {
    description "Vultr ${VULTR_PLATFORM} IPv6";
    local ${SOURCE_IPV6} as ${LOCAL_ASN};
    neighbor ${VULTR_NEIGHBOR_V6} as ${VULTR_ASN};
    multihop 2;
    password "${BGP_PASSWORD}";

    ipv6 {
        import all;
        export filter vultr_export_ipv6;
        next hop self;
    };
}

EOF
fi
